### ISSUE TITLE
No username/password cred info in Waston services

### ISSUE THREAD

**Issue by zhangtbj** [IBM/cognitive-social-crm#46]
Hi,

I am trying this demo for Call of Code, I see we need to input username/password for Waston services, like:
```
  "CONVERSATION_API_URL": "",
  "CONVERSATION_API_USER": "",
  "CONVERSATION_API_PASSWORD": "",
  "CONVERSATION_CLASSIFICATION_WORKSPACE_ID": "",

  "NLU_API_USER": "",
  "NLU_API_PASSWORD": "",

  "TONE_ANALYZER_USER": "",
  "TONE_ANALYZER_PASSWORD": "",
```

But after I created Waston service in bluemix, and check their cred info, there is no username and password info any more:

I can only get this kind of info:
```

KEY NAME | DATE CREATED | ACTIONS |  
-- | -- | -- | --
Auto-generated service credentials | Jul 19, 2018 - 04:08:43 | View credentials |  
Credentials-1 | Jul 19, 2018 - 05:30:48 | View credentials |  
{   "apikey": "xxx",   "iam_apikey_description": "Auto generated apikey during resource-key operation for Instance - crn:v1:bluemix:public:conversation:au-syd:a/xxx:xxx-74406a2b668b::",   "iam_apikey_name": "auto-generated-apikey-xxx",   "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",   "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/xxx::serviceid:ServiceId-95f12db5-xxxx",   "url": "https://gateway-syd.watsonplatform.net/assistant/api" }
```

I tried to input `iam_apikey_name` as username and `apikey` as password, but after start the node app and check the tweet, I cannot see anything and the Waston service should not work.

Have you tried in the latest Waston service , or did I operate any wrong?

Thanks a lot!

**Comment by zhangtbj** [comment]
I got the error message from `cf logs --recent`:

```
2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR Unhandled error for request POST /watson-conversation/send?access_token=50SUwZo9d6HyZo8IBxzWPKsUtD2xAcBXuuNqfnYcdDZgq8jcMj3opDK7aZG4Rsqh: Error: Unauthorized
   2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR     at Request._callback (/home/vcap/app/node_modules/watson-developer-cloud/lib/requestwrapper.js:87:15)
   2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR     at Request.self.callback (/home/vcap/app/node_modules/watson-developer-cloud/node_modules/request/request.js:188:22)
   2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR     at emitTwo (events.js:106:13)
   2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR     at Request.emit (events.js:194:7)
   2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR     at Request.<anonymous> (/home/vcap/app/node_modules/watson-developer-cloud/node_modules/request/request.js:1171:10)
   2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR     at emitOne (events.js:96:13)
   2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR     at Request.emit (events.js:191:7)
   2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR     at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/watson-developer-cloud/node_modules/request/request.js:1091:12)
   2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR     at Object.onceWrapper (events.js:293:19)
   2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR     at emitNone (events.js:91:20)
   2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR     at IncomingMessage.emit (events.js:188:7)
   2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR     at endReadableNT (_stream_readable.js:975:12)
   2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR     at _combinedTickCallback (internal/process/next_tick.js:80:11)
   2018-07-19T17:26:19.86+0800 [APP/PROC/WEB/0] ERR     at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by scottdangelo** [comment]
You are correct. The Watson service has changed from username/password to apikey. We are in the process of updating this code pattern to use the new apikey. Please watch for this issue to be fixed in the future.

**Comment by zhangtbj** [comment]
Thanks! @scottdangelo , we are investigating this demo and maybe many other `Call for Code` users are trying it, hope it can be ready soon. Thanks! :)

**Comment by sanjeevghimire** [comment]
@zhangtbj the code should work if you create credentials other than `us-east` or `sydney` region, which will give you username+password as oppose to IAM api key.

**Comment by zhangtbj** [comment]
HI @sanjeevghimire Thanks for the help, yes! after I change to US-South, I can get username and password. Now my demo works fine, thanks!
