### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by Dom137** [IBM/cognitive-social-crm#77]
I've been following the instructions from the readme, but at the point where I'm trying to run the app locally, I'm getting this:
`[dom@dlehr-mbp17:/Data/Projects/SocialNOC/cognitive-social-crm]>npm run start

> cognitive-social-crm@1.0.0 start /Data/Projects/SocialNOC/cognitive-social-crm
> concurrently "npm run start:client" "npm run start:server"

sh: concurrently: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! cognitive-social-crm@1.0.0 start: `concurrently "npm run start:client" "npm run start:server"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the cognitive-social-crm@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2019-05-09T14_15_00_855Z-debug.log`

I than tried "npm run start:server", but it fails with this:
`[dom@dlehr-mbp17:/Data/Projects/SocialNOC/cognitive-social-crm]>npm run start:server

> cognitive-social-crm@1.0.0 start:server /Data/Projects/SocialNOC/cognitive-social-crm
> cd server && npm start

> server@1.0.0 start /Data/Projects/SocialNOC/cognitive-social-crm/server
> npm run build:live

> server@1.0.0 build:live /Data/Projects/SocialNOC/cognitive-social-crm/server
> NODE_ENV=development nodemon --exec ./node_modules/.bin/ts-node -- server.ts

[nodemon] 1.18.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `./node_modules/.bin/ts-node server.ts`

/Data/Projects/SocialNOC/cognitive-social-crm/server/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/util/Logger.ts(42,31): error TS2345: Argument of type 'any[]' is not assignable to parameter of type '[]'.
  Types of property 'length' are incompatible.
    Type 'number' is not assignable to type '0'.
src/util/Logger.ts(49,33): error TS2345: Argument of type 'any[]' is not assignable to parameter of type '[]'.

    at createTSError (/Data/Projects/SocialNOC/cognitive-social-crm/server/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/Data/Projects/SocialNOC/cognitive-social-crm/server/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/Data/Projects/SocialNOC/cognitive-social-crm/server/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/Data/Projects/SocialNOC/cognitive-social-crm/server/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Data/Projects/SocialNOC/cognitive-social-crm/server/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
[nodemon] app crashed - waiting for file changes before starting...`

Any help is very much appreciated

Thanks and BR
Dominic

**Comment by sanjeevghimire** [comment]
Are you running this on Windows? there is a note that` windows are currently not supported `in the readme.

**Comment by Dom137** [comment]
Hi, 

thanks for your reply. Nope, I'm running this on Mac OS.
In addition, when trying to build server (so that I can deploy it to the cloud), I'm getting this:
`npm run build:server

> cognitive-social-crm@1.0.0 build:server /Data/Projects/SocialNOC/cognitive-social-crm
> cd server && npm run build


> server@1.0.0 build /Data/Projects/SocialNOC/cognitive-social-crm/server
> node ./node_modules/.bin/tsc

src/util/Logger.ts:42:31 - error TS2345: Argument of type 'any[]' is not assignable to parameter of type '[]'.
  Types of property 'length' are incompatible.
    Type 'number' is not assignable to type '0'.

42     consoleLog.apply(console, args);
                                 ~~~~

src/util/Logger.ts:49:33 - error TS2345: Argument of type 'any[]' is not assignable to parameter of type '[]'.

49     consoleError.apply(console, args);
                                   ~~~~


Found 2 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! server@1.0.0 build: `node ./node_modules/.bin/tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the server@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2019-05-10T06_04_57_042Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cognitive-social-crm@1.0.0 build:server: `cd server && npm run build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cognitive-social-crm@1.0.0 build:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2019-05-10T06_04_57_065Z-debug.log`

I'm using:
- npm version 6.9.0
- Angular:
---
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
---

**Comment by Dom137** [comment]
FYI, in "src/util/Logger.ts", I commented lines 42 and 49 and it compiled. I was also able run it locally and deploy it the cloud...

**Comment by mubashirqasim** [comment]
I am also getting the same error on AWS Linux EC2. 
Here is the error log:

[ec2-user@ip-172-31-18-93 cognitive-social-crm]$ npm run build

> cognitive-social-crm@1.0.0 prebuild /home/ec2-user/cognitive-social-crm
> rm -rf dist


> cognitive-social-crm@1.0.0 build /home/ec2-user/cognitive-social-crm
> concurrently "npm run build:client" "npm run build:server"

[0]
[0] > cognitive-social-crm@1.0.0 build:client /home/ec2-user/cognitive-social-crm
[0] > cd client && npm run build:prod
[0]
[1]
[1] > cognitive-social-crm@1.0.0 build:server /home/ec2-user/cognitive-social-crm
[1] > cd server && npm run build
[1]
[1]
[1] > server@1.0.0 build /home/ec2-user/cognitive-social-crm/server
[1] > node ./node_modules/.bin/tsc
[1]
[0]
[0] > cognitive-social-crm@0.0.1 build:prod /home/ec2-user/cognitive-social-crm/client
[0] > ./node_modules/@angular/cli/bin/ng build --prod --aot
[0]
[0]
[0] @angular/compiler-cli@7.2.13 requires typescript@'>=3.1.1 <3.3' but 2.7.2 was found instead.
[0] Using this version can result in undefined behaviour and difficult to debug problems.
[0]
[0] Please run the following command to install a compatible version of TypeScript.
[0]
[0]     npm install typescript@'>=3.1.1 <3.3'
[0]
[0] To disable this warning run "ng config cli.warnings.typescriptMismatch false".
[0]
[0]
[0] Date: 2019-05-21T09:33:44.236Z
[0] Hash: 41c9356094bf1f203ce2
[0] Time: 6106ms
[0] chunk {0} runtime.26209474bfa8dc87a77c.js (runtime) 1.41 kB [entry] [rendered]
[0] chunk {1} main.01ecbc0fcff9207e8cde.js (main) 128 bytes [initial] [rendered]
[0] chunk {2} polyfills.a723c36635c3a098c2aa.js (polyfills) 130 bytes [initial] [rendered]
[0] chunk {3} styles.f680323462ea0c7e361e.css (styles) 139 kB [initial] [rendered]
[0]
[0] ERROR in The Angular Compiler requires TypeScript >=3.1.1 and <3.3.0 but 2.7.2 was found instead.
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! cognitive-social-crm@0.0.1 build:prod: `./node_modules/@angular/cli/bin/ng build --prod --aot`
[0] npm ERR! Exit status 1
[0] npm ERR!
npm ERR! Failed at the cognitive-social-crm@0.0.1 build:prod script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0]
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /home/ec2-user/.npm/_logs/2019-05-21T09_33_44_297Z-debug.log
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! cognitive-social-crm@1.0.0 build:client: `cd client && npm run build:prod`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the cognitive-social-crm@1.0.0 build:client script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0]
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /home/ec2-user/.npm/_logs/2019-05-21T09_33_44_314Z-debug.log
[0] npm run build:client exited with code 1
[1] src/util/Logger.ts(42,31): error TS2345: Argument of type 'any[]' is not assignable to parameter of type '[]'.
[1]   Types of property 'length' are incompatible.
[1]     Type 'number' is not assignable to type '0'.
[1] src/util/Logger.ts(49,33): error TS2345: Argument of type 'any[]' is not assignable to parameter of type '[]'.
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 2
[1] npm ERR! server@1.0.0 build: `node ./node_modules/.bin/tsc`
[1] npm ERR! Exit status 2
[1] npm ERR!
[1] npm ERR! Failed at the server@1.0.0 build script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/ec2-user/.npm/_logs/2019-05-21T09_33_47_357Z-debug.log
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 2
[1] npm ERR! cognitive-social-crm@1.0.0 build:server: `cd server && npm run build`
[1] npm ERR! Exit status 2
[1] npm ERR!
[1] npm ERR! Failed at the cognitive-social-crm@1.0.0 build:server script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/ec2-user/.npm/_logs/2019-05-21T09_33_47_369Z-debug.log
[1] npm run build:server exited with code 2
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cognitive-social-crm@1.0.0 build: `concurrently "npm run build:client" "npm run build:server"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cognitive-social-crm@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2019-05-21T09_33_47_382Z-debug.log
[ec2-user@ip-172-31-18-93 cognitive-social-crm]$ Connection to ec2-13-236-177-66.ap-southeast-2.compute.amazonaws.com closed by remote host.
Connection to ec2-13-236-177-66.ap-southeast-2.compute.amazonaws.com closed.

**Comment by jndg01** [comment]
Hello, I have the same error as the other person, here I send everything that the ubuntu terminal appears to me, I wait for your answer and I remain attentive to be able to solve the problem soon thanks for your attention.


user@ibmdemo:~/cognitive-social-crm/server$ npm run build

> server@1.0.0 build /home/user/cognitive-social-crm/server
> node ./node_modules/.bin/tsc

src/util/Logger.ts:42:31 - error TS2345: Argument of type 'any[]' is not assignable to parameter of type '[]'.
  Types of property 'length' are incompatible.
    Type 'number' is not assignable to type '0'.

42     consoleLog.apply(console, args);
                                 ~~~~

src/util/Logger.ts:49:32 - error TS2345: Argument of type 'any[]' is not assignable to parameter of type '[]'.

49    consoleError.apply(console, args);
                                  ~~~~


Found 2 errors.


npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! server@1.0.0 build: `node ./node_modules/.bin/tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the server@1.0.0 build script 'node ./node_modules/.bin/tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/.bin/tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/cognitive-social-crm/server/npm-debug.log

**Comment by sanjeevghimire** [comment]
#79  should address this. Please try again after it is merged. thanks.

**Comment by mubashirqasim** [comment]
The works now. However, the output is not coming as shown in the screenshot.

Do you have a link to working example?

![image](https://user-images.githubusercontent.com/8086373/58226223-d59f1c00-7d79-11e9-9b07-a860f0e4ae83.png)

**Comment by sanjeevghimire** [comment]
#79 fixes it.
