### ISSUE TITLE
Installlation error

### ISSUE THREAD

**Issue by mubashirqasim** [IBM/cognitive-social-crm#78]
Hi there, 

I get the following error when I run `npm run app-install`

Any help is much appreciated.

```
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/ubuntu/cognitive-social-crm/client/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/ubuntu/cognitive-social-crm/client/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/ubuntu/cognitive-social-crm/client/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/ubuntu/cognitive-social-crm/client/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/ubuntu/cognitive-social-crm/client/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/ubuntu/cognitive-social-crm/client/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:149:21)
gyp ERR! System Linux 4.15.0-1032-aws
gyp ERR! command "/usr/bin/node" "/home/ubuntu/cognitive-social-crm/client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/ubuntu/cognitive-social-crm/client/node_modules/node-sass
gyp ERR! node -v v12.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by sanjeevghimire** [comment]
you need to run:
`npm run start`
which should start the app after `npm install`. may be node needs to be udpated.

probable #79 might fix it.

**Comment by sanjeevghimire** [comment]
#79 fixes it.
